#!/bin/bash

# Extract values with jq (name, type, weight, height)
jq -r '.name, .types[0].type.name, .weight, .height' data.json | \
awk 'NR==1{ name=$0 } 
     NR==2{ type=$0 } 
     NR==3{ weight=$0 } 
     NR==4{ height=$0 } 
     END {
       printf "%s is of type %s, weighs %skg, and is %.1fm tall.\n", name, type, weight, height/10
     }' | \
# Capitalize first letter of name and type using sed
sed -E 's/^(.)/\U\1/; s/type ([a-z])/\type \U\1/'
